# Generated by Django 3.2.9 on 2022-01-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_alter_bookinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/', verbose_name='封面图片'),
        ),
    ]
